name: Docker Build and Push # Tên của workflow, sẽ hiển thị trên GitHub Actions

on:
  push:
    branches:
      - main   #Workflow này sẽ được kích hoạt mỗi khi có code được đẩy (push) lên nhánh main.

jobs:
  build-and-push:  #Định nghĩa một job duy nhất có tên build-and-push.
    runs-on: ubuntu-latest  #Job này sẽ chạy trên một máy ảo Ubuntu mới nhất do GitHub cung cấp.
    steps:  #Các bước tuần tự mà job sẽ thực hiện.
      - name: Checkout code 
        uses: actions/checkout@v4  #Sử dụng actions/checkout@v4 để clone mã nguồn từ repository vào máy ảo.

      - name: Log in to Docker Hub
        uses: docker/login-action@v3  #Sử dụng docker/login-action@v3 để đăng nhập vào Docker Hub.
        with:
          username: ${{ secrets.DOCKERHUB_TOKEN }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}        #Nó sử dụng DOCKER_USERNAME và DOCKER_TOKEN mà bạn đã cấu hình trong GitHub Secrets.

      - name: Build and push user-service image
        uses: docker/build-push-action@v5              #Sử dụng docker/build-push-action@v5 để:   
        with:
          context: ./services/user-service              #Chỉ định thư mục chứa Dockerfile và mã nguồn của user-service.
          push: true                                    #Yêu cầu đẩy image lên Docker Hub sau khi build thành công.
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/simple-math-solver-user-service:latest    #Định nghĩa tên và tag của image. Nó sẽ có dạng your_docker_username/simple-math-solver-user-service:latest.

      - name: Build and push math-solver-service image
        uses: docker/build-push-action@v5
        with:
          context: ./services/math-solver-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/simple-math-solver-math-solver-service:latest
